    - name: Write updated whitelist.json
      ansible.builtin.copy:
        content: |
          [
            {
              "uuid": "a3b32431-4cb4-4e86-9c71-2253a0ff5b1e",
              "name": "HashiCorp_Nic"
            }
          ]
        dest: /etc/minecraft/whitelist.json
        mode: '0644'
      register: write_result