- name: Update minecraft whitelist
  hosts: all
  become: false
  vars:
    minecraft_usernames:
      - "SheriffJackson"
  tasks:
    - name: Add players to minecraft whitelist
      ansible.builtin.command: "rcon-cli --password password whitelist add {{ item }}"
      register: rcon_result
      loop: "{{ minecraft_usernames }}"
         
    - name: Display RCON command results
      ansible.builtin.debug:
        var: rcon_result.results