- name: Minecraft Install with Vault SSH prereqs
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Include minecraft tasks"
      include_tasks: minecraft.yml

    - name: "Include vault tasks"
      include_tasks: vault_ssh.yml
